"""Pydantic models for the virtual staging feature."""
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, validator


class ProjectStatus(str, Enum):
    UPLOADING = "uploading"
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class ItemStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class StagingSettings(BaseModel):
    variations_per_room: int = Field(5, description="Number of variations to generate per room (1-10)")
    model: str = Field("gpt-image-2", description="Image generation model")
    quality: str = Field("high", description="Image quality setting")
    size: str = Field("auto", description="Image size")

    @validator("variations_per_room")
    def validate_variations(cls, v):
        if v < 1 or v > 10:
            raise ValueError("variations_per_room must be between 1 and 10")
        return v


class GenerationMetadata(BaseModel):
    model: Optional[str] = None
    adapted_prompt: Optional[str] = None
    tokens_used: Optional[int] = None
    generation_time_ms: Optional[int] = None


class Variation(BaseModel):
    id: str
    image_url: Optional[str] = None
    thumbnail_url: Optional[str] = None
    status: str = Field(ItemStatus.PENDING, description="Variation generation status")
    error: Optional[str] = None
    generation_metadata: Optional[GenerationMetadata] = None


class Room(BaseModel):
    id: str
    label: str = Field(..., description="Room label, e.g. 'Living Room', 'Backyard'")
    original_image_url: str = Field(..., description="Blob storage URL of uploaded original")
    original_thumbnail_url: Optional[str] = None
    status: str = Field(ItemStatus.PENDING, description="Room processing status")
    error: Optional[str] = None
    variations: List[Variation] = Field(default_factory=list)
    prompt_addendum: Optional[str] = Field(
        None,
        description=(
            "Optional per-room clarification appended to the project prompt for "
            "every future generation of this room. Existing variations are not "
            "regenerated when this changes."
        ),
    )


class StagingProject(BaseModel):
    id: str
    name: str
    prompt: str
    status: str = Field(ProjectStatus.UPLOADING, description="Overall project status")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    rooms: List[Room] = Field(default_factory=list)
    settings: StagingSettings = Field(default_factory=StagingSettings)
    folder_path: Optional[str] = None
    design_brief: Optional[Dict[str, Any]] = Field(None, description="Structured design brief from AI conversation")
    analyses: Optional[List[Dict[str, Any]]] = Field(None, description="Image analysis results")
    prompt_summary: Optional[str] = Field(
        None,
        description=(
            "≤240-char summary of ``prompt`` for collapsed display on the "
            "project page. Generated by ``PromptSummarizer`` on create and "
            "on every PATCH that changes ``prompt`` (issue 013 of the "
            "image-pipeline-and-project-ux-overhaul PRD). Editing this "
            "field never triggers regeneration."
        ),
    )


class CreateProjectRequest(BaseModel):
    name: str = Field(..., description="Project name", examples=["Modern Minimalist Refresh"])
    prompt: str = Field(..., description="Overall styling direction", examples=["Clean lines, warm wood tones, lots of greenery"])
    settings: StagingSettings = Field(default_factory=StagingSettings)


class UpdateRoomRequest(BaseModel):
    """Partial-update body for ``PATCH /projects/{id}/rooms/{rid}``.

    Issue history:

    - Originally added in issue 003 of the projects-page-improvements
      PRD with a single editable field (``prompt_addendum``).
    - Extended in issue 004 of the project-settings-completeness PRD
      with the ``label`` field so the new ``ProjectRoomsManager`` UI
      on the Project Settings sheet can rename rooms in place.

    Field semantics (mirrors ``UpdateProjectRequest``):

    - ``label``: required project state when present. Sending ``null``
      raises 422 — clients shouldn't clear required fields. Empty /
      whitespace-only is also 422. The endpoint trims surrounding
      whitespace before persisting.

    - ``prompt_addendum``: ``None`` and empty/whitespace-only are
      meaningful — they explicitly clear the addendum. The endpoint
      normalizes both to ``None`` before persisting so the persisted
      shape stays consistent with the composer's "absent" rule.

    Both fields are independent and ``__fields_set__``-aware in the
    handler. Critically, this means a label-only PATCH does NOT
    silently clear an existing addendum (which would happen if the
    handler defaulted the absent field to ``None`` and unconditionally
    wrote it back). Other Room fields (``status``, ``variations``,
    ``original_image_url``) are derived from generation activity and
    must not be edited through this endpoint.
    """
    label: Optional[str] = Field(
        None,
        description=(
            "Display label for the room. Trimmed before persisting. "
            "Send null or empty to receive a 422 (required)."
        ),
    )
    prompt_addendum: Optional[str] = Field(
        None,
        description=(
            "Per-room clarification appended to the project prompt for future "
            "generations of this room. Pass null or omit to clear."
        ),
    )

    @validator("label")
    def _label_non_empty(cls, v):
        # Pydantic v1: validator only fires when the field is explicitly
        # present in the input (the ``Optional[str] = None`` default
        # short-circuits before the validator if the field is absent).
        # So this only fires for explicit values, including explicit
        # ``null``.
        if v is None:
            raise ValueError("label cannot be null; omit the field to leave unchanged")
        if not v.strip():
            raise ValueError("label cannot be empty or whitespace-only")
        return v


class UpdateProjectRequest(BaseModel):
    """Partial-update body for ``PATCH /projects/{id}`` (issue 002 of
    the projects-page-improvements PRD).

    Every field is optional — omit to leave the persisted value
    untouched. The endpoint applies updates ONLY to the fields the
    client actually sends (uses Pydantic's ``__fields_set__`` to
    distinguish "not present" from "explicitly null").

    Field semantics:

    - ``name`` / ``prompt`` / ``settings``: required project state.
      Sending ``null`` for any of these raises 422 — clients shouldn't
      clear required fields. Empty / whitespace-only ``name`` and
      ``prompt`` are also 422.

    - ``settings``: when present, the endpoint MERGES the supplied keys
      onto the persisted settings rather than replacing the whole
      object. This means ``{settings: {variations_per_room: 3}}`` only
      updates that one key — ``model``/``quality``/``size`` keep their
      persisted values.

    - ``design_brief``: ``None`` is meaningful — it clears the brief.

    The endpoint NEVER modifies ``rooms``, ``analyses``, or ``status`` —
    those are owned by the generation pipeline. The shape of this
    request body intentionally has no fields for them so a misbehaving
    client cannot edit them through this endpoint.
    """
    name: Optional[str] = Field(None, description="Project display name.")
    prompt: Optional[str] = Field(None, description="Top-level styling prompt.")
    settings: Optional[StagingSettings] = Field(
        None,
        description=(
            "Partial settings update — only the keys you supply are merged "
            "onto the persisted settings."
        ),
    )
    design_brief: Optional[Dict[str, Any]] = Field(
        None,
        description="Structured design brief; pass null to clear.",
    )
    prompt_summary: Optional[str] = Field(
        None,
        description=(
            "Override the auto-generated ≤240-char summary. When omitted "
            "AND ``prompt`` is sent, the server regenerates the summary "
            "via ``PromptSummarizer``. When omitted and ``prompt`` is "
            "absent, the persisted summary is left untouched. Issue 013 "
            "of the image-pipeline-and-project-ux-overhaul PRD."
        ),
    )

    @validator("name")
    def _name_non_empty(cls, v):
        # Validators in Pydantic v1 run when the field is explicitly
        # present in the input (including when sent as ``null``), but
        # the ``Optional[str] = None`` default short-circuits before the
        # validator if the field is absent — so this only fires for
        # explicit values.
        if v is None:
            raise ValueError("name cannot be null; omit the field to leave unchanged")
        if not v.strip():
            raise ValueError("name cannot be empty or whitespace-only")
        return v

    @validator("prompt")
    def _prompt_non_empty(cls, v):
        if v is None:
            raise ValueError("prompt cannot be null; omit the field to leave unchanged")
        if not v.strip():
            raise ValueError("prompt cannot be empty or whitespace-only")
        return v

    @validator("settings")
    def _settings_not_explicit_null(cls, v):
        # Same rationale as above — the field default is None, so
        # absent-from-input does not invoke the validator. An explicit
        # null in the JSON body parses to None and lands here.
        if v is None:
            raise ValueError("settings cannot be null; omit the field to leave unchanged")
        return v

    @validator("prompt_summary")
    def _prompt_summary_non_empty(cls, v):
        # Same convention as ``name``/``prompt``: explicit null is a 422
        # because clients shouldn't blank a derived display field — if
        # they want it regenerated, send the new ``prompt`` and let the
        # endpoint recompute. Empty/whitespace-only strings are also
        # 422 — a literal empty summary would render as a confusing
        # blank line on the project page; if the prompt itself is
        # blank, the summary derived from it is also blank and the
        # endpoint handles that pathway server-side. Length cap (≤240)
        # is enforced server-side via ``truncate_to_summary`` rather
        # than at the validator boundary so a single overshoot doesn't
        # 422 a request the user can otherwise satisfy.
        if v is None:
            raise ValueError(
                "prompt_summary cannot be null; omit the field to leave unchanged"
            )
        if not v.strip():
            raise ValueError(
                "prompt_summary cannot be empty or whitespace-only"
            )
        return v


class EditPromptRequest(BaseModel):
    """Body for ``POST /projects/{id}/rooms/{rid}/variations/{vid}/edit-prompt``
    (issue 004 of the projects-page-improvements PRD).

    The user-supplied ``adapted_prompt`` is the ENTIRE base of the new
    variation's prompt — ``BriefGeneratorService.brief_to_prompts`` is
    bypassed entirely on this path so the user's text is authoritative.
    The room's ``prompt_addendum`` (if any) is still composed onto the
    end of the prompt by ``PromptComposer``.

    Required field; empty / whitespace-only → 422 (clients shouldn't
    send no-op edits — there's a Cancel button for that).
    """
    adapted_prompt: str = Field(
        ...,
        description=(
            "User-typed prompt that becomes the variation's base. Bypasses "
            "the design brief; the room's prompt_addendum is still appended."
        ),
    )

    @validator("adapted_prompt")
    def _adapted_prompt_non_empty(cls, v):
        if v is None:
            raise ValueError("adapted_prompt is required")
        if not v.strip():
            raise ValueError("adapted_prompt cannot be empty or whitespace-only")
        return v


class UploadRoomsResponse(BaseModel):
    project_id: str
    rooms_added: int
    rooms: List[Room]


class ProjectResponse(BaseModel):
    project: StagingProject


class ProjectListResponse(BaseModel):
    projects: List[StagingProject]
    total: int
